version: '3.7'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/src:/app/src
    env_file: .env
    environment:
      - NODE_ENV=development
    image: bitsbid-server