version: '3.7'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/src:/app/src
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
      - ./client/build:/app/client/build
    env_file: .env
    image: bitsbid-server
    ports:
      - ${PORT}:${PORT}