version: '3.7'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    image: bitsbid-client    
    ports:
      - 3000:3000
