version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend.dev
    volumes:
      - ./server/src:/app/src
      - ./client/build:/app/client/build
    env_file: .env
    image: bitsbid-server
    ports:
      - ${PORT}:${PORT}