version: '3.7'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    depends_on:
      - backend
    image: bitsbid-client    
    ports:
      - 3000:3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/src:/app/src
    env_file: .env
    image: bitsbid-server
    ports:
      - ${PORT}:${PORT}